### ISSUE TITLE
Python Import Error

### ISSUE THREAD

**Issue by zoeleeee** [chrischoy/knn_cuda#1]
When I finish "make" according to your readme, there is only some warning tips. But then while I try 'python example.py' , it tells me that

ImportError:knn.so:undefined symbol: _ZTIN5boost6python7objects21py_function_impl_baseE

I doubt whether I finished "make" well. I find many solutions in network but it still doesn't work.
I have Ubuntu 16.04 and Cuda compilation tools, release 8.0.
What's your environment? What tips you have after you "make" ?

**Comment by yulongtzzz** [comment]
Please execute make first. Then 

g++ -shared build/knn.o build/knn_cuda.o build/knn_cuda_link.o -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -L/usr/local/lib -lcuda -lcudart -lcudadevrt -lboost_python -lpython2.7  -o knn.so

It works well in my laptop.

**Comment by chrischoy** [comment]
There was a minor error in the makefile. Please try compiling it now after pulling.
